//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#ifndef EDROOMDEPLOYMENT_H_
#define EDROOMDEPLOYMENT_H_
 
#include <edroom_glue/edroomdf.h>
#include <public/edroomsl_iface_v1.h>
 
 
//******************************************************************************
// include deployment edroom components
 
#include <public/cccontrolplant_iface_v1.h>
#include <public/ccledtask_iface_v1.h>
#include <public/cchttpservertask_iface_v1.h>
#include <public/cckeyscantask_iface_v1.h>
#include <public/ccrs232task_iface_v1.h>
#include <public/ccmonitor_iface_v1.h>
// ***********************************************************************
// class CEDROOMSystemMemory
// ***********************************************************************
 
class CEDROOMSystemMemory{
 
	//!Messages Memory of component comp2
	CEDROOMMessage	comp2Messages[10];
	bool	comp2MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp2QueueNodes[13];
	bool	comp2QueueNodesMarks[13];
 
	//!Messages Memory of component comp3
	CEDROOMMessage	comp3Messages[10];
	bool	comp3MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp3QueueNodes[13];
	bool	comp3QueueNodesMarks[13];
 
	//!Messages Memory of component comp4
	CEDROOMMessage	comp4Messages[10];
	bool	comp4MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp4QueueNodes[13];
	bool	comp4QueueNodesMarks[13];
 
	//!Messages Memory of component comp5
	CEDROOMMessage	comp5Messages[10];
	bool	comp5MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp5QueueNodes[13];
	bool	comp5QueueNodesMarks[13];
 
	//!Messages Memory of component comp6
	CEDROOMMessage	comp6Messages[10];
	bool	comp6MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp6QueueNodes[13];
	bool	comp6QueueNodesMarks[13];
 
	//!Messages Memory of component comp7
	CEDROOMMessage	comp7Messages[10];
	bool	comp7MessagesMarks[10];
	CEDROOMQueue::CQueueNode	comp7QueueNodes[13];
	bool	comp7QueueNodesMarks[13];
 
	public:
 
	CCControlPlant::CEDROOMMemory comp2Memory;
	CCLEDTask::CEDROOMMemory comp3Memory;
	CCHTTPServerTask::CEDROOMMemory comp4Memory;
	CCKeyScanTask::CEDROOMMemory comp5Memory;
	CCRS232Task::CEDROOMMemory comp6Memory;
	CCMonitor::CEDROOMMemory comp7Memory;
 
//!Set Memory
	void SetMemory();
};
 
class CEDROOMSystemCommSAP{
 
	 friend class CEDROOMSystemDeployment;
//!Communication Service Access Point
 
	CEDROOMLocalCommSAP m_localCommSAP;
 
 
//!Conections
 
	CEDROOMLocalConnection connections[9];
 
	CCControlPlant   * mp_comp2;
	CCLEDTask   * mp_comp3;
	CCHTTPServerTask   * mp_comp4;
	CCKeyScanTask   * mp_comp5;
	CCRS232Task   * mp_comp6;
	CCMonitor   * mp_comp7;
 
 
//!Set Components
 
	void SetComponents(CCControlPlant   *p_comp2,
							CCLEDTask   *p_comp3,
							CCHTTPServerTask   *p_comp4,
							CCKeyScanTask   *p_comp5,
							CCRS232Task   *p_comp6,
							CCMonitor   *p_comp7);
 
 
//Signal Conversion
 
	static TEDROOMSignal C6RS232Task_PMonitorDataStream__C7Monitor_PRS232DataStream(TEDROOMSignal signal);
	static TEDROOMSignal C7Monitor_PRS232DataStream__C6RS232Task_PMonitorDataStream(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C5KeyScanTask_PMonitorDataStream__C7Monitor_PKeybDataStream(TEDROOMSignal signal);
	static TEDROOMSignal C7Monitor_PKeybDataStream__C5KeyScanTask_PMonitorDataStream(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C7Monitor_PSwWatchdog__C3LEDTask_PSwWatchdog5(TEDROOMSignal signal);
	static TEDROOMSignal C3LEDTask_PSwWatchdog5__C7Monitor_PSwWatchdog(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C5KeyScanTask_PSwWatchdog__C3LEDTask_PSwWatchdog4(TEDROOMSignal signal);
	static TEDROOMSignal C3LEDTask_PSwWatchdog4__C5KeyScanTask_PSwWatchdog(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C6RS232Task_PSwWatchdog__C3LEDTask_PSwWatchdog3(TEDROOMSignal signal);
	static TEDROOMSignal C3LEDTask_PSwWatchdog3__C6RS232Task_PSwWatchdog(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C2ControlPlant_PKeybCommand__C5KeyScanTask_PCommand(TEDROOMSignal signal);
	static TEDROOMSignal C5KeyScanTask_PCommand__C2ControlPlant_PKeybCommand(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C2ControlPlant_PRS232Command__C6RS232Task_PCommand(TEDROOMSignal signal);
	static TEDROOMSignal C6RS232Task_PCommand__C2ControlPlant_PRS232Command(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C3LEDTask_PSwWatchdog2__C2ControlPlant_PSwWatchdog(TEDROOMSignal signal);
	static TEDROOMSignal C2ControlPlant_PSwWatchdog__C3LEDTask_PSwWatchdog2(TEDROOMSignal signal);
 
//Signal Conversion
 
	static TEDROOMSignal C3LEDTask_PSwWatchdog__C4HTTPServerTask_PSwWatchdog(TEDROOMSignal signal);
	static TEDROOMSignal C4HTTPServerTask_PSwWatchdog__C3LEDTask_PSwWatchdog(TEDROOMSignal signal);
 
 
//!Register Interfaces
	void RegisterInterfaces();
 
//!Set Local Connections
	void SetLocalConnections();
 
//!Set Remote Connections
	void SetRemoteConnections();
 
//!Set Connections
	void SetConnections();
 
};
 
class CEDROOMSystemDeployment{
 
//!Kernel
	Pr_Kernel	kernel;
 
#ifdef CONFIG_EDROOMDEPLOYMENT_NEED_TASK
 
//!Main Task
static Pr_TaskRV_t main_task(Pr_TaskP_t);
 
#endif
	CEDROOMSystemMemory   systemMemory;
	CEDROOMSystemCommSAP  systemCommSAP;
 
	CCControlPlant   * mp_comp2;
	CCLEDTask   * mp_comp3;
	CCHTTPServerTask   * mp_comp4;
	CCKeyScanTask   * mp_comp5;
	CCRS232Task   * mp_comp6;
	CCMonitor   * mp_comp7;
 
	public:
 
	CEDROOMSystemDeployment();
 
//!Deployment Configuration
	void Config(CCControlPlant   *p_comp2,
					CCLEDTask   *p_comp3,
					CCHTTPServerTask   *p_comp4,
					CCKeyScanTask   *p_comp5,
					CCRS232Task   *p_comp6,
					CCMonitor   *p_comp7);
 
//!Deployment Start
	void Start();
 
//!StartComponents
	void StartComponents();
//!Config Components
 
	CCControlPlant::CEDROOMMemory 		* GetComp2Memory(){return &systemMemory.comp2Memory;}
	CCLEDTask::CEDROOMMemory 		* GetComp3Memory(){return &systemMemory.comp3Memory;}
	CCHTTPServerTask::CEDROOMMemory 		* GetComp4Memory(){return &systemMemory.comp4Memory;}
	CCKeyScanTask::CEDROOMMemory 		* GetComp5Memory(){return &systemMemory.comp5Memory;}
	CCRS232Task::CEDROOMMemory 		* GetComp6Memory(){return &systemMemory.comp6Memory;}
	CCMonitor::CEDROOMMemory 		* GetComp7Memory(){return &systemMemory.comp7Memory;}
 
};
#endif
