//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
#include <fsl_debug_console.h>
 
//******************************************************************************
// include deployment edroom components
 
#include <public/icuasw_iface_v1.h>
#include <public/ccepdmanager_iface_v1.h>
#include <public/cctm_channelctrl_iface_v1.h>
#include <public/cchk_fdirmng_iface_v1.h>
#include <public/ccbkgtcexec_iface_v1.h>

#include <public/sc_channel_drv_iface_v1.h>
#include <public/emu_sc_channel_drv_slib_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;

#endif
 


int main (void){



#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;

#endif

	ICUASW	*comp1 = new ICUASW(1, 13, EDROOMprioVeryLow, 8192, systemDeployment.GetComp1Memory());
	CCEPDManager	*comp2 = new CCEPDManager(2, 11, EDROOMprioHigh, 1024, systemDeployment.GetComp2Memory());
	CCTM_ChannelCtrl	*comp3= new CCTM_ChannelCtrl(3, 10, EDROOMprioVeryHigh, 1024, systemDeployment.GetComp3Memory());
	CCHK_FDIRMng	*comp4 = new CCHK_FDIRMng(4, 14, EDROOMprioNormal, 1024, systemDeployment.GetComp4Memory());
	CCBKGTCExec	*comp5 = new CCBKGTCExec(5, 11, EDROOMprioVeryLow, 1024, systemDeployment.GetComp5Memory());
	Init_sc_channel();
	systemDeployment.Config(comp1, comp2, comp3, comp4, comp5);
 
	systemDeployment.Start();
 
	return 0;
 
}
