//##############################################################################
//###############     This file has been generated by EDROOM     ###############
//##############################################################################
 
#include <public/edroom_glue.h>
#include <fsl_debug_console.h>
 
//******************************************************************************
// include deployment edroom components
 
#include <public/icuasw_iface_v1.h>
#include <public/ccepdmanager_iface_v1.h>
#include <public/cctm_channelctrl_iface_v1.h>
#include <public/cchk_fdirmng_iface_v1.h>
#include <public/ccbkgtcexec_iface_v1.h>
 
#ifdef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
 
 
 
int main (void){
 
 
 
#ifndef CONFIG_EDROOMBP_DEPLOYMENT_NEED_TASK
 
	CEDROOMSystemDeployment systemDeployment;
 
#endif
	PRINTF("\r\nSize of systemDeployment:%d\r\n", sizeof(systemDeployment));
	PRINTF("\r\nSystem deployment:%p\r\n", systemDeployment);
	ICUASW	comp1(1, 13, EDROOMprioVeryLow, 8192, systemDeployment.GetComp1Memory());
	PRINTF("\r\ncomp1:%p\r\n", comp1);
	CCEPDManager	comp2(2, 11, EDROOMprioHigh, 1024, systemDeployment.GetComp2Memory());
	PRINTF("\r\ncomp2:%p\r\n", comp2);
	CCTM_ChannelCtrl	comp3(3, 10, EDROOMprioVeryHigh, 1024, systemDeployment.GetComp3Memory());
	PRINTF("\r\ncomp3:%p\r\n", comp3);
	CCHK_FDIRMng	comp4(4, 14, EDROOMprioNormal, 1024, systemDeployment.GetComp4Memory());
	PRINTF("\r\ncomp4:%p\r\n", comp4);
	CCBKGTCExec	comp5(5, 11, EDROOMprioVeryLow, 1024, systemDeployment.GetComp5Memory());
	PRINTF("\r\ncomp5:%p\r\n", comp5);

 
	systemDeployment.Config(&comp1, &comp2, &comp3, &comp4, &comp5);
 
	systemDeployment.Start();
 
	return 0;
 
}
