################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/croutine.c \
C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/event_groups.c \
C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/portable/MemMang/heap_4.c \
C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/list.c \
C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/queue.c \
C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/tasks.c \
C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/timers.c 

OBJS += \
./osswpackages/freertos/src/croutine.o \
./osswpackages/freertos/src/event_groups.o \
./osswpackages/freertos/src/heap_4.o \
./osswpackages/freertos/src/list.o \
./osswpackages/freertos/src/queue.o \
./osswpackages/freertos/src/tasks.o \
./osswpackages/freertos/src/timers.o 

C_DEPS += \
./osswpackages/freertos/src/croutine.d \
./osswpackages/freertos/src/event_groups.d \
./osswpackages/freertos/src/heap_4.d \
./osswpackages/freertos/src/list.d \
./osswpackages/freertos/src/queue.d \
./osswpackages/freertos/src/tasks.d \
./osswpackages/freertos/src/timers.d 


# Each subdirectory must supply rules for building sources it contributes
osswpackages/freertos/src/croutine.o: C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/croutine.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C Compiler'
	riscv32-unknown-elf-gcc -msmall-data-limit=8 -mno-save-restore -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -ffreestanding -fno-builtin -Wall  -g -DDEBUG -DCPU_RV32M1_ri5cy -DFSL_RTOS_FREE_RTOS -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\exit_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\edroombp_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include\platform" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswinterfaces\freertosapi\include\public" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\stdarg_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\xprintf_iface_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\xprintf_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\config\include" -I../../../../../../../rtos/freertos_9.0.0/Source/portable/GCC/RISCY -I../../../../../../../rtos/freertos_9.0.0/Source/include -I../../../../../../../RISCV -I../../../../../../../devices -I../../.. -I../../../../.. -I../../../../../../../rtos/freertos_9.0.0/Source -I../../../../../../../devices/RV32M1/drivers -I../../../../../../../devices/RV32M1/utilities -I../../../../../../../devices/RV32M1/utilities/io -I../../../../../../../devices/RV32M1/utilities/str -I../../../../../../../devices/RV32M1/utilities/log -I../../../../../../../devices/RV32M1 -I../.. -I../../../../../freertos_config_board/ri5cy -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -std=gnu99 -march=rv32imcxpulpv2 -Wa,-march=rv32imcxpulpv2 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

osswpackages/freertos/src/event_groups.o: C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/event_groups.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C Compiler'
	riscv32-unknown-elf-gcc -msmall-data-limit=8 -mno-save-restore -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -ffreestanding -fno-builtin -Wall  -g -DDEBUG -DCPU_RV32M1_ri5cy -DFSL_RTOS_FREE_RTOS -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\exit_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\edroombp_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include\platform" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswinterfaces\freertosapi\include\public" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\stdarg_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\xprintf_iface_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\xprintf_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\config\include" -I../../../../../../../rtos/freertos_9.0.0/Source/portable/GCC/RISCY -I../../../../../../../rtos/freertos_9.0.0/Source/include -I../../../../../../../RISCV -I../../../../../../../devices -I../../.. -I../../../../.. -I../../../../../../../rtos/freertos_9.0.0/Source -I../../../../../../../devices/RV32M1/drivers -I../../../../../../../devices/RV32M1/utilities -I../../../../../../../devices/RV32M1/utilities/io -I../../../../../../../devices/RV32M1/utilities/str -I../../../../../../../devices/RV32M1/utilities/log -I../../../../../../../devices/RV32M1 -I../.. -I../../../../../freertos_config_board/ri5cy -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -std=gnu99 -march=rv32imcxpulpv2 -Wa,-march=rv32imcxpulpv2 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

osswpackages/freertos/src/heap_4.o: C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/portable/MemMang/heap_4.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C Compiler'
	riscv32-unknown-elf-gcc -msmall-data-limit=8 -mno-save-restore -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -ffreestanding -fno-builtin -Wall  -g -DDEBUG -DCPU_RV32M1_ri5cy -DFSL_RTOS_FREE_RTOS -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\exit_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\edroombp_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include\platform" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswinterfaces\freertosapi\include\public" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\stdarg_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\xprintf_iface_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\xprintf_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\config\include" -I../../../../../../../rtos/freertos_9.0.0/Source/portable/GCC/RISCY -I../../../../../../../rtos/freertos_9.0.0/Source/include -I../../../../../../../RISCV -I../../../../../../../devices -I../../.. -I../../../../.. -I../../../../../../../rtos/freertos_9.0.0/Source -I../../../../../../../devices/RV32M1/drivers -I../../../../../../../devices/RV32M1/utilities -I../../../../../../../devices/RV32M1/utilities/io -I../../../../../../../devices/RV32M1/utilities/str -I../../../../../../../devices/RV32M1/utilities/log -I../../../../../../../devices/RV32M1 -I../.. -I../../../../../freertos_config_board/ri5cy -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -std=gnu99 -march=rv32imcxpulpv2 -Wa,-march=rv32imcxpulpv2 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

osswpackages/freertos/src/list.o: C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/list.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C Compiler'
	riscv32-unknown-elf-gcc -msmall-data-limit=8 -mno-save-restore -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -ffreestanding -fno-builtin -Wall  -g -DDEBUG -DCPU_RV32M1_ri5cy -DFSL_RTOS_FREE_RTOS -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\exit_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\edroombp_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include\platform" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswinterfaces\freertosapi\include\public" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\stdarg_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\xprintf_iface_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\xprintf_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\config\include" -I../../../../../../../rtos/freertos_9.0.0/Source/portable/GCC/RISCY -I../../../../../../../rtos/freertos_9.0.0/Source/include -I../../../../../../../RISCV -I../../../../../../../devices -I../../.. -I../../../../.. -I../../../../../../../rtos/freertos_9.0.0/Source -I../../../../../../../devices/RV32M1/drivers -I../../../../../../../devices/RV32M1/utilities -I../../../../../../../devices/RV32M1/utilities/io -I../../../../../../../devices/RV32M1/utilities/str -I../../../../../../../devices/RV32M1/utilities/log -I../../../../../../../devices/RV32M1 -I../.. -I../../../../../freertos_config_board/ri5cy -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -std=gnu99 -march=rv32imcxpulpv2 -Wa,-march=rv32imcxpulpv2 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

osswpackages/freertos/src/queue.o: C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/queue.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C Compiler'
	riscv32-unknown-elf-gcc -msmall-data-limit=8 -mno-save-restore -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -ffreestanding -fno-builtin -Wall  -g -DDEBUG -DCPU_RV32M1_ri5cy -DFSL_RTOS_FREE_RTOS -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\exit_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\edroombp_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include\platform" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswinterfaces\freertosapi\include\public" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\stdarg_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\xprintf_iface_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\xprintf_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\config\include" -I../../../../../../../rtos/freertos_9.0.0/Source/portable/GCC/RISCY -I../../../../../../../rtos/freertos_9.0.0/Source/include -I../../../../../../../RISCV -I../../../../../../../devices -I../../.. -I../../../../.. -I../../../../../../../rtos/freertos_9.0.0/Source -I../../../../../../../devices/RV32M1/drivers -I../../../../../../../devices/RV32M1/utilities -I../../../../../../../devices/RV32M1/utilities/io -I../../../../../../../devices/RV32M1/utilities/str -I../../../../../../../devices/RV32M1/utilities/log -I../../../../../../../devices/RV32M1 -I../.. -I../../../../../freertos_config_board/ri5cy -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -std=gnu99 -march=rv32imcxpulpv2 -Wa,-march=rv32imcxpulpv2 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

osswpackages/freertos/src/tasks.o: C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/tasks.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C Compiler'
	riscv32-unknown-elf-gcc -msmall-data-limit=8 -mno-save-restore -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -ffreestanding -fno-builtin -Wall  -g -DDEBUG -DCPU_RV32M1_ri5cy -DFSL_RTOS_FREE_RTOS -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\exit_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\edroombp_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include\platform" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswinterfaces\freertosapi\include\public" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\stdarg_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\xprintf_iface_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\xprintf_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\config\include" -I../../../../../../../rtos/freertos_9.0.0/Source/portable/GCC/RISCY -I../../../../../../../rtos/freertos_9.0.0/Source/include -I../../../../../../../RISCV -I../../../../../../../devices -I../../.. -I../../../../.. -I../../../../../../../rtos/freertos_9.0.0/Source -I../../../../../../../devices/RV32M1/drivers -I../../../../../../../devices/RV32M1/utilities -I../../../../../../../devices/RV32M1/utilities/io -I../../../../../../../devices/RV32M1/utilities/str -I../../../../../../../devices/RV32M1/utilities/log -I../../../../../../../devices/RV32M1 -I../.. -I../../../../../freertos_config_board/ri5cy -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -std=gnu99 -march=rv32imcxpulpv2 -Wa,-march=rv32imcxpulpv2 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

osswpackages/freertos/src/timers.o: C:/Vega/rv32m1_sdk_riscv/rtos/freertos_9.0.0/Source/timers.c
	@echo 'Building file: $<'
	@echo 'Invoking: GNU RISC-V Cross C Compiler'
	riscv32-unknown-elf-gcc -msmall-data-limit=8 -mno-save-restore -O0 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-common -ffreestanding -fno-builtin -Wall  -g -DDEBUG -DCPU_RV32M1_ri5cy -DFSL_RTOS_FREE_RTOS -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\exit_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\edroombp_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\pswpackages\freertosapi_freertos_x86_v1\include\platform" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswinterfaces\freertosapi\include\public" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\stdarg_iface_c99\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swinterfaces\xprintf_iface_v1\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\swpackages\xprintf_slib_head\include" -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\config\include" -I../../../../../../../rtos/freertos_9.0.0/Source/portable/GCC/RISCY -I../../../../../../../rtos/freertos_9.0.0/Source/include -I../../../../../../../RISCV -I../../../../../../../devices -I../../.. -I../../../../.. -I../../../../../../../rtos/freertos_9.0.0/Source -I../../../../../../../devices/RV32M1/drivers -I../../../../../../../devices/RV32M1/utilities -I../../../../../../../devices/RV32M1/utilities/io -I../../../../../../../devices/RV32M1/utilities/str -I../../../../../../../devices/RV32M1/utilities/log -I../../../../../../../devices/RV32M1 -I../.. -I../../../../../freertos_config_board/ri5cy -I"C:\Vega\rv32m1_sdk_riscv\boards\rv32m1_vega\rtos_examples\freertos_tfg\ri5cy\riscveclipse\osswpackages\freertos\src\portable\GCC\Posix" -std=gnu99 -march=rv32imcxpulpv2 -Wa,-march=rv32imcxpulpv2 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


