#ifndef XPRINTF_SLIB__CONFIG_H
#define XPRINTF_SLIB__CONFIG_H

#include <public/config.h>

#define CONFIG_SWP_XPRINTF_SLIB_CHANNEL_OUTPUT_NULL CONFIG_SWP_XPRINTF_SLIB_HEAD_CHANNEL_OUTPUT_NULL
#define CONFIG_SWP_XPRINTF_SLIB_CHANNEL_OUTPUT_STDOUT CONFIG_SWP_XPRINTF_SLIB_HEAD_CHANNEL_OUTPUT_STDOUT
#define CONFIG_SWP_XPRINTF_SLIB_CHANNEL_1_OUTPUT CONFIG_SWP_XPRINTF_SLIB_HEAD_CHANNEL_1_OUTPUT
#define CONFIG_SWP_XPRINTF_SLIB_CHANNEL_0_OUTPUT CONFIG_SWP_XPRINTF_SLIB_HEAD_CHANNEL_0_OUTPUT
//#define CONFIG_SWP_XPRINTF_SLIB_RTEMSAPI_4_8_IMPR_RTEMS_4_8_IMPR_ANY_ANY_ANY_STDOUT_UART_CHANNEL CONFIG_SWP_XPRINTF_SLIB_HEAD_RTEMSAPI_4_8_IMPR_RTEMS_4_8_IMPR_ANY_ANY_ANY_STDOUT_UART_CHANNEL

/*PROTECTED REGION ID(xprintf_slib_config_h) ENABLED START*/


    // This is a protected region as long as you keep the marks :-)


/*PROTECTED REGION END*/

#endif // XPRINTF_SLIB__CONFIG_H
